# Generated by Django 5.1.15 on 2026-05-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_tiktok_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
