# Generated by Django 5.1.15 on 2026-04-28 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_rev_created_03e07d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place_name'], name='reviews_rev_place_n_f82d07_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['latitude', 'longitude'], name='reviews_rev_latitud_651803_idx'),
        ),
    ]
